.pre-commit-config.yaml
examples/vmseries_scaleset/README.md
examples/vmseries_scaleset/example.tfvars
examples/vmseries_scaleset/main.tf
examples/vmseries_scaleset/outputs.tf
modules/vmss/README.md
modules/vmss/outputs.tf
modules/vmss/variables.tf

Enforce tflint naming convention `snake_case` instead of `dashed-names` or `UPPERCASE`.
Enforce pinning down the external module sources, instead of taking those from the `master` branch.
Ease the code review process - the devs will be notified by CI job about basic code issues, not by a human.
Example `init` and `apply` per README.

refactor: enforce tflint naming convention `snake_case`

---

modules/loadbalancer/README.md
modules/loadbalancer/main.tf
modules/loadbalancer/variables.tf

For module loadbalancer, add input `tags`.
Cloud tagging is quite a usual requirement.
`apply` of the examples

feat(loadbalancer): add input `tags`

---

CONTRIBUTING.md

Use the same versions of tools in CONTRIBUTING as in
`scripts/install.sh`.
Devs will benefit from consistent behavior between their pre-commit and CI's.
Running the instructions locally.

fix CONTRIBUTING use current versions of tools

---

modules/vnet/README.md

docs(vnet): update README of the vnet module

---

CONTRIBUTING.md

Signed-off-by: Stephen Steiner <ssteiner@paloaltonetworks.com>
Updated CONTRIBUTING.md to be more clear regarding the pre-commit script process.
The doc didn't make it clear that if pre-commit changed any files, that a failure would occur and that it is normal for this.
Docs only, no testing needed
- Docs

docs: update CONTRIBUTING.md     FIXES #128

---

examples/panorama/main.tf
examples/transit_vnet_common/main.tf
examples/transit_vnet_dedicated/main.tf
examples/vmseries/main.tf
examples/vmseries_scaleset/main.tf

Add missing variable required for overrides special character list in password generator.
It fix special character list used for password creation.
I take portions of code used for password creation with missing variable and run a couple of times and see in output if there is non specified character from the special character list.

fix: missing variable for special character

---

modules/virtual_machine/main.tf
modules/virtual_machine/variables.tf
modules/vmseries/variables.tf

Update module code to work with currently supported Azure provider versions. Resolves #180 
Make module usable.
Module has been applied using example code.

fix(modules/virtual_machine): Update module to work with provider v3

---

.github/CODEOWNERS

Add Code Owners based on the people actively working with the code.
Automatically add reviewers to all new PRs.
N/A

chore: introduce codeowners

---

modules/appgw/README.md
modules/appgw/outputs.tf

PR delivers changes in ``appgw`` module in order to output Application Gateway backend address pool.
Support for VMSS behind application gateway was required in customer project, so in order to fulfil in future similar requests, PR was prepared. Output from ``appgw`` module is used while calling ``vmss`` module.
Changes were tested in the lab before delivering it in the project to customer.

feat(module/appgw): add identifier of the Application Gateway backend address pool

---

.github/workflows/pr_ci.yml
.github/workflows/release_ci.yml

Add support for TF 1.4 in CI pipelines.
Since 1.4 release we should add support for this version in CI workflows to make sure our code is compatible with that version.

ci: introduce terraform 1.4

---

README.md

docs(README.md): add badges to readme

---

modules/vmss/README.md

Adding additional documentation for the `roll_instances_when_required` provider feature in the `vmss` module's README.
closes #256 
n/a
docs

docs: upgrade_mode = "Manual" documentation

---

examples/common_vmseries/README.md
examples/dedicated_vmseries/README.md
examples/dedicated_vmseries_and_autoscale/README.md
examples/standalone_panorama/README.md
examples/standalone_vmseries/README.md

Updates to READMEs for Automation Hub launch
Updates to READMEs for Automation Hub launch
N/A
N/A
- Docs

docs: Updates to READMEs for Automation Hub launch

---

.github/workflows/lint_pr_title.yml
.github/workflows/pr_ci.yml
.github/workflows/pre-commit-update.yml
.github/workflows/release_ci.yml

A workflow to update `pre-commit` dependencies.
Since dependabot cannot track `.pre-commit.yaml` yet, this  workflow can do the job. It will pick up the pre-commit config file, loop through all repos and look for the latest release tag. Then a PR with the updated pre-commit configuration will be created.
If the PR gets created, updated a pre-commit sub-workflow will be run to test changes. Results are posted as a comment in the created PR. 
Run on a copy of Azure repo

ci(pre-commit): Pre commit dependencies update workflow

---

.github/workflows/lint_pr_title.yml
.github/workflows/pr_ci.yml
.github/workflows/release_ci.yml

use full tagging on reusable workflows
Workaround for `v1` not working on release CI

ci: fix tagging on workflows

---

examples/standalone_panorama/README.md

Make the Panorama example live in Orchestration Hub
Make the Panorama example live in Orchestration Hub
Previous pan.dev testing

docs: Make the Panorama example live in Orchestration Hub

---

examples/dedicated_vmseries_and_autoscale/README.md

Update Dedicated VMSeries with autoscaling example README for SWFW Hub
- Documentation

docs: dedicated vmseries autoscale README for SWFW Hub

---

examples/standalone_panorama/README.md
modules/panorama/README.md

Update standalone panorama example README for SWFW Hub
- Documentation

docs: standalone panorama README for SWFW Hub

---

examples/dedicated_vmseries_and_autoscale/README.md
examples/standalone_panorama/README.md

Updating frontmatter in the READMEs to publish examples to Software Hub

docs: update frontmatter

---

modules/virtual_machine/main.tf

Missing dependencies result in resource removal failing in the first run and destroy needs to be rerun.
Enable consistent removal, important especially for automated deployments.
n/a

fix(modules/virtual_machine): Add dependencies for backend pool association

---

.github/workflows/apply-command.yml
.github/workflows/idempotence-command.yml
.github/workflows/plan-command.yml
.github/workflows/pr_ci.yml
.github/workflows/pre-commit-update.yml
.github/workflows/release_ci.yml
.github/workflows/sca-command.yml
.github/workflows/validate-command.yml

Follow changes in v.2.2 branch of common workflows repository.
* move back to minor release tagging
* add `cloud` parameter to chatops workflows
n/a

ci: follow updates in breaking changes release v.2.2.0

---

.github/workflows/chatops.yml

falling back to the original approach for chatops, this pulls back the changes done in #317

chore: fallback to gh app generated token

---

examples/common_vmseries_and_autoscale/README.md

Needed to convert image to PNG to display correctly in pan.dev.
pan.dev sync workflow currently supports png files only.

docs(examples/common_vmseries_and_autoscale): Change image to PNG

---

examples/common_vmseries/main.tf
examples/common_vmseries_and_autoscale/main.tf
examples/dedicated_vmseries/main.tf
examples/dedicated_vmseries_and_autoscale/main.tf
examples/gwlb_with_vmseries/main.tf
examples/standalone_panorama/main.tf
examples/standalone_vmseries/main.tf
examples/test_infrastructure/main.tf
examples/vnet/main.tf

Fix subnet naming, remove prefixes in subnet names

fix(examples): subnet naming - no prefixing

---

examples/common_vmseries/example.tfvars
examples/common_vmseries_and_autoscale/example.tfvars
examples/dedicated_vmseries/example.tfvars
examples/dedicated_vmseries_and_autoscale/example.tfvars
examples/standalone_panorama/example.tfvars
examples/standalone_vmseries/example.tfvars
examples/test_infrastructure/example.tfvars

Fixed NSG and RT assignments to subnets in examples (tfvars files only).
#337 
Tested with one of the examples.

refactor: vnet tfvars in examples

---

.github/workflows/pre-commit-update.yml

Fix pre-commit update workflow
There was a type-o in one of the parameters preventing the workflow to run

ci: Update pre-commit-update.yml

---

.github/workflows/pre-commit-update.yml
examples/common_vmseries/variables.tf
examples/common_vmseries_and_autoscale/variables.tf
examples/dedicated_vmseries/variables.tf
examples/dedicated_vmseries_and_autoscale/variables.tf
examples/gwlb_with_vmseries/example.tfvars
examples/gwlb_with_vmseries/variables.tf
examples/standalone_panorama/variables.tf
examples/standalone_vmseries/variables.tf
examples/test_infrastructure/variables.tf
modules/vnet/README.md
modules/vnet/main.tf
modules/vnet/variables.tf

based on an issue from @migara #357 
proven to work on one of the examples:

refactor: add support for disable bgp route propagation

---

examples/common_vmseries/main.tf
examples/common_vmseries/variables.tf
examples/common_vmseries_and_autoscale/main.tf
examples/common_vmseries_and_autoscale/variables.tf
examples/dedicated_vmseries/main.tf
examples/dedicated_vmseries/variables.tf
examples/dedicated_vmseries_and_autoscale/example.tfvars
examples/dedicated_vmseries_and_autoscale/main.tf
examples/dedicated_vmseries_and_autoscale/variables.tf
examples/natgw/example.tfvars
examples/natgw/main.tf
examples/natgw/variables.tf
examples/natgw/versions.tf
examples/standalone_vmseries/main.tf
examples/standalone_vmseries/variables.tf
modules/natgw/.header.md
modules/natgw/README.md
modules/natgw/main.tf
modules/natgw/outputs.tf
modules/natgw/variables.tf
modules/natgw/versions.tf

PR delivers changes for vnet_peering:
- `README.md` adjusted to new style with additional header file
- minimum Terraform version set to 1.3
- refactor variables:
- descriptions
- types with optionals
- default values
- validations
- simplify `main.tf` by removing not required `try`
- remove name generation logic from the module
- add terraform registry reference
#330 
I checked that module using "natgw" example.

refactor(module/natgw)!: module refactor and adjusted examples
