examples/panorama/README.md
examples/panorama/main.tf
examples/panorama/outputs.tf
examples/panorama/variables.tf
modules/panorama/README.md
modules/panorama/main.tf
modules/panorama/variables.tf

Subnet cidr is an input, but can only be modified if priv ip is not
hardcoded. Making it an input as well.
Minor fixes for the module, non-breaking.

fix(examples/panorama): input for priv ip

---

modules/panorama/main.tf
modules/panorama/versions.tf

- Changed Version Constraint to Include TF 0.15
- Added SKU = "Standard" to Public IP in Panorama Module.
I use TF 0.15 and I was receiving this error when deploying Panorama within an Availabilty Zone:
```
Error: updating Network Interface: (Name "mgmt" / Resource Group "panorama"): network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ComputeResourceZoneConstraintDoesNotMatchPublicIPAddressZoneConstraint" Message="Compute resource /subscriptions/137***016/resourceGroups/panorama/providers/Microsoft.Compute/virtualMachines/pano-deploy has a zone constraint 1 but the PublicIPAddress /subscriptions/137***016/resourceGroups/panorama/providers/Microsoft.Network/publicIPAddresses/pano_pip used by the compute resource via NetworkInterface or …
```

fix(examples/panorama): change Public IP to SKU "Standard"

---

examples/bootstrap/README.md
examples/bootstrap/versions.tf
examples/panorama/README.md
examples/panorama/versions.tf
examples/transit_vnet_common/README.md
examples/transit_vnet_common/versions.tf
examples/vmseries_scaleset/README.md
examples/vmseries_scaleset/versions.tf
examples/vnet/README.md
examples/vnet/versions.tf
modules/bootstrap/README.md
modules/bootstrap/versions.tf
modules/loadbalancer/README.md
modules/loadbalancer/versions.tf
modules/panorama/README.md
modules/panorama/versions.tf
modules/vmseries/README.md
modules/vmseries/versions.tf
modules/vmss/README.md
modules/vmss/versions.tf
modules/vnet/README.md
modules/vnet/versions.tf

Allow Terraform version 0.14.x on every module and every example.
Previously the latest compatible version was 0.13.x.
All examples have been applied and then destroyed.

feat: allow terraform 0.14.x on every module

---

examples/bootstrap/README.md
examples/bootstrap/outputs.tf
examples/bootstrap/versions.tf
examples/panorama/README.md
examples/panorama/outputs.tf
examples/panorama/versions.tf
examples/transit_vnet_common/README.md
examples/transit_vnet_common/outputs.tf
examples/transit_vnet_common/versions.tf
examples/vmseries_scaleset/README.md
examples/vmseries_scaleset/outputs.tf
examples/vmseries_scaleset/versions.tf
examples/vnet/README.md
examples/vnet/main.tf
examples/vnet/versions.tf
modules/bootstrap/README.md
modules/bootstrap/outputs.tf
modules/bootstrap/versions.tf
modules/loadbalancer/README.md
modules/loadbalancer/main.tf
modules/loadbalancer/versions.tf
modules/panorama/README.md
modules/panorama/versions.tf
modules/vmseries/README.md
modules/vmseries/outputs.tf
modules/vmseries/versions.tf
modules/vmss/README.md
modules/vmss/versions.tf
modules/vnet/README.md
modules/vnet/versions.tf

Pass the `sensitive` status marked by providers onto the outputs. This
will be a hard requirement from Terraform version 0.15 onwards.
The sensitive outputs are best viewed with `-json` flag.
For docs, remove the `$ ` prompts because of the linting rule:
"MD014/commands-show-output: Dollar signs used before commands without
showing output"
This is the recommended version, so allowing it is a major use case.
When using provider older than 2.46, it visibly warns:
`"resource_group_name": [DEPRECATED] in resource "azurerm_lb_backend_address_pool"`
Since the examples cannot stay on 2.42 now, pinning them
to the latest version, which is 2.58 (as of now).
It's debatable whether this change is actually Breaking. But for now, I stay on the safe side here.
Apply all the examples.
- Breaking change …

feat!: Mark selected outputs as sensitive, allow tf-0.15, require azurerm-2.46+

---

examples/vmseries/README.md
examples/vmseries/example.tfvars
examples/vmseries/main.tf
examples/vmseries/outputs.tf
examples/vmseries/variables.tf
examples/vmseries/versions.tf
modules/vmseries/README.md
modules/vmseries/main.tf

Create a very minimal example. It's the only one which is 0.12.29
compatible, because it does not employ module `depends_on` or module
`for_each` anywhere.
As this example is not intended to be copy-pasted into maintainable
codebases, a majority of usual variables are inlined into the main.tf
code. This way users see everything together, which can aid their
learning.
When avzone is an empty string, treat it the same as null.
docs(vmseries): fix usage in the README 
`apply` per example's instruction

feat(examples): Add a minimal vmseries example

---

modules/bootstrap/main.tf

Bootstrap module didn't create plugins/ folder described here: https://docs.paloaltonetworks.com/vm-series/9-0/vm-series-deployment/bootstrap-the-vm-series-firewall/prepare-the-bootstrap-package.html

bug: Add missing folder in bootstrap module (TERRAM-112)

---

examples/transit_vnet_dedicated/main.tf

Correct the files used for bootstrapping outbound VM-Series.
Previously the same storage account was used for outbound VM-Series as for the inbound. Ouch. 😖 
Create a `terraform.tfvars` file and copy the content of `example.tfvars` into it, adjust if needed. Use Panorama. Make sure the outbound firewalls have configured different `dgname` than inbound firewalls.
```sh
terraform init
terraform apply
terraform ouput -json password
terraform destory
```

fix a bug in examples/transit_vnet_dedicated

---

README.md

Non-absolute links are dead in Terraform Registry
Fixes #132
Also - update contributing link to point to common documentation.
Please see linked issue.
Invalid links should not exist in Terraform Registry.
n/a
n/a

fix(docs): correct dead links in main README

---

.releaserc.json

The current GH release links are pointing to a dead link
Example: https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/pull/127#issuecomment-949645618

ci: fix GH release link

---

modules/vmss/README.md
modules/vmss/main.tf
modules/vmss/variables.tf

Updates for follwing PR https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/pull/130
Once approved and merged, the original one will be closed.
See linked PR.
Apply using Terraform 1.1.4. Tested without a value in a variable, as well as using an id of existing prefix.
n/a

feat(vmss): support for public IP prefix for mgmt interface

---

modules/bootstrap/main.tf

The way we calculated md5 checksums for bootstrap files' management was based on `md5` terraform function. This function takes a Unicode string as input. To make it work you have to use a `file` function that 'reads' a file and provides it's content as an output.
This works fine for text files. It does not for binary. 
To fix it a different function `filemd5` was used. It calculates a checksum directly from the file. So it works with both: text and binary files.
Some organisations would like to use bootstrapping for updating (for example) plugins. This is especially important when dealing with ScaleSets and autoscalling (the update is done during bootstrapping). W/O this change it is impossible to manage non-text files using bootstrap module.  
This was tested by creating an …

fix(module/bootstrap): calculate md5 checksum also for non text files

---

.gitignore
.pre-commit-config.yaml

Ignore .terraform.lock.hcl in git and when running terraform-docs.
If the file is taken into account when generating docs it can cause a sort of a "race condition" between local and CI hook executions.
Checked local vs. CI results.

chore: Ignore .terraform.lock.hcl

---

examples/bootstrap/README.md
examples/panorama/README.md
examples/transit_vnet_common/README.md
examples/transit_vnet_dedicated/README.md
examples/vmseries/README.md
examples/vmseries_scaleset/README.md
examples/vnet/README.md
modules/appgw/README.md
modules/bootstrap/README.md
modules/loadbalancer/README.md
modules/panorama/README.md
modules/vmseries/README.md
modules/vmss/README.md
modules/vnet/README.md

Update READMEs to include changes generated by terraform-docs after enabling hcl lock file ignoring (https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/pull/151).
Those changes for some reason were not introduced together with the hook config change and can result in extra changes for non-related PRs.
Docs only change

docs: Update autogenerated READMEs

---

examples/bootstrap/README.md
examples/bootstrap/versions.tf
examples/panorama/README.md
examples/panorama/versions.tf
examples/transit_vnet_common/README.md
examples/transit_vnet_common/versions.tf
examples/transit_vnet_dedicated/README.md
examples/transit_vnet_dedicated/versions.tf
examples/vmseries/README.md
examples/vmseries/versions.tf
examples/vmseries_scaleset/README.md
examples/vmseries_scaleset/versions.tf
examples/vnet/README.md
modules/appgw/README.md
modules/bootstrap/README.md
modules/bootstrap/versions.tf
modules/loadbalancer/README.md
modules/panorama/README.md
modules/panorama/versions.tf
modules/vmseries/README.md
modules/vmss/README.md
modules/vnet/README.md

Mac M1-based machines require random provider to be minimum v3.1
Able to use modules on Mac M1-based machines
Mac M1-based machines fail to use modules with older versions of the random provider
Increase version numbers in versions.tf for the modules (and examples ideally)
Use modules on a Mac M1-based machine
Terraform v1.1.9 on darwin_arm64
macOS 12.4

157-upgrade-random-provider-versions

---

examples/bootstrap/README.md
examples/panorama/README.md
examples/transit_vnet_common/README.md
examples/transit_vnet_dedicated/README.md
examples/vmseries/README.md
examples/vmseries_scaleset/README.md
modules/bootstrap/README.md
modules/panorama/README.md

Fix extra provider sections in README files.
It affect all PRs, even with unrelated changes.
n/a

fix(docs): Remove duplicated provider sections

---

examples/bootstrap/README.md
examples/bootstrap/versions.tf
examples/panorama/README.md
examples/panorama/versions.tf
examples/transit_vnet_common/README.md
examples/transit_vnet_common/versions.tf
examples/transit_vnet_dedicated/README.md
examples/transit_vnet_dedicated/versions.tf
examples/vmseries/README.md
examples/vmseries/versions.tf
examples/vmseries_scaleset/README.md
examples/vmseries_scaleset/versions.tf
examples/vnet/README.md
examples/vnet/versions.tf
modules/bootstrap/README.md
modules/bootstrap/versions.tf
modules/loadbalancer/README.md
modules/loadbalancer/versions.tf
modules/panorama/README.md
modules/panorama/versions.tf
modules/virtual_machine/versions.tf
modules/vmseries/README.md
modules/vmseries/versions.tf
modules/vmss/README.md
modules/vmss/versions.tf
modules/vnet/README.md
modules/vnet/versions.tf

The current version requirements for Azure were `~>3.7.0`. Even though `~>` was used, the version has patch value included which prevents using more recent 3.x provider versions.
Also the version requirements were removed from examples, this way we relay on minimum versions from modules. The example is only a glue-code and does not relay on the provider directly. 
We're pinned to Azure provider version 3.7.0.
`terraform init` was run to check if a newer version then 3.7.0 will be used. 

fix: add relaxed azure provider version requirements

---

.github/actions/validate_tf/action.yml
.github/workflows/tf_validate_ver.yml

A manually triggered workflow (for the moment) that runs `terraform validate` against all modules and examples. It does it for different TF versions. Currently these are: 0.15.0, 1.0.0, 1.2.0.
Code is run in threads, meaning that each module/example is tested against all TF versions at the same time. 
Since testing required commits to `develop` branch, development was done on a [fork repo, `develop` branch](https://github.com/FoSix/terraform-azurerm-vmseries-modules/actions/runs/2846100286). This PR is only the final code. 
We need to make sure that while developing the code with the latest TF versions the code stays compatible with the declared range. Doing this manually is almost impossible. 
Workflow was run locally using `act` and on a forked repo (a commit to develop branch was …

feat(ci): A new workflow to validate TF code against different TF versions

---

.github/workflows/ci.yml
README.md
examples/bootstrap/README.md
examples/transit_vnet_common/README.md
examples/transit_vnet_common/variables.tf
examples/transit_vnet_dedicated/README.md
examples/transit_vnet_dedicated/variables.tf
examples/vmseries/README.md
examples/vmseries_scaleset/README.md
examples/vmseries_scaleset/variables.tf
modules/panorama/variables.tf
modules/virtual_machine/variables.tf
modules/vmseries/variables.tf
modules/vmss/variables.tf

Adding `sensitive` flag to variables that will hold sensitive data, like passwords or user data bootstrap options.
Additional comments were added to READMEs to emphasise that example hosted in this repository might contain sensitive data and should not be used in this form in production. 
Encouraged by #205 
an example was run with the use of `sensitive` flag to verify that sensitive information was deducted from the CLI output

fix: adding sensitive property to password and bootstrap_option variables

---

.github/workflows/ci.yml
makefile
modules/vmss/README.md
modules/vmss/main.tf
modules/vmss/variables.tf
modules/vmss/versions.tf

Replace the `scale_in_policy` property with `scale_in` block introduced in version `3.21` of the Azure Terraform Provider.
The `scale_in_policy` property is obsolete and will be removed in provider version `4.x`.
A VMSS example was deployed to make sure that the interface of the `vmss` module did not change.

feat(module/vmss): fix update deprecated vmss properties

---

modules/virtual_machine/.README.md
modules/virtual_machine/main.tf
modules/virtual_machine/variables.tf

Add support for key-based auth in `virtual_machine` module.
Extend module flexibility.
Apply custom example code.

feat(module/virtual_machine): add ssh key-pair auth

---

modules/appgw/README.md
modules/appgw/main.tf
modules/appgw/outputs.tf
modules/appgw/variables.tf

With domain_name_label, Azure will generate a fqdn for the Azure Application Gateway Public IP in <domain_name_label>.<region>.cloudapp.azure.com format.
For testing it makes easy to get an fqdn that resolves to Application Gateway public IP. 
Tested on example code with the domain_name_label attribute and removing it.

feat(module/appgw): add domain_name_label support for AppGW Public IP

---

modules/natgw/README.md
modules/natgw/main.tf
modules/natgw/outputs.tf
modules/natgw/variables.tf
modules/natgw/versions.tf

This PR introduces a new module that can be used to create a NAT Gateway.
NAT GW is a the only Azure method of handling the outgoing traffic that can prevent SNAT port exhaustion.  Therefore a module that automates creation of this and related resources is introduced with this PR.
This module is capable of:
* creating a new NAT GW with either a Public IP or Public IP prefix 
* creating a new NAT GW and reusing existing Public IP or Public IP Prefix
* only sourcing an existing NAT GW.
In all 3 cases the NAT GW will be associated with subnets provided as a map of subnet IDs.
Sample code based on Common Ref Architecture was deployed. 

feat(module/natgw): introduce NAT GW module

---

modules/natgw/Makefile

Add `Makefile` to NatGW module
`Makefile` for NaTGW module is missing due to which the release pipeline fail.
makefile was run locally 

ci(module/natgw): adding missing makefile to fix failing CI pipelines

---

modules/vmseries/main.tf

For destroy operations, force the LB backend association to be destroyed 1<sup>st</sup>. 
W/o that manual dependency, during destroy operations, a race condition can happen, when VM is being destroyed before the NIC - LB backend association. In such case the destroy operation fails with an error. The problem is not the order but the fact that the VM is in a 'destroying' phase while the the destroy operation is run on the association. 
This fix can also close #199 as the problem described in that issue is triggered only when a destroy operation 1<sup>st</sup> fails due to the described race condition. 
Existing code/example have been run to prove that the race condition cannot be reproduced.

fix(module/vmseries): fix destroy sequence for LB backends

---

.github/actions/plan_apply/action.yml
.github/actions/sub_cleanup/action.yml
.github/workflows/lint_pr_title.yml
.github/workflows/pr_ci.yml
.github/workflows/release_ci.yml
examples/common_vmseries/Makefile
examples/dedicated_vmseries/Makefile
examples/dedicated_vmseries_and_autoscale/Makefile
examples/standalone_panorama/Makefile
examples/standalone_vmseries/Makefile
makefile.sh

Introducing possibility to run `terraform plan/apply` on examples.
All tests available up to this point were just static tests. With this PR we are extending the tests by providing a framework for running the actual deployments. The most important changes are:
* all `pre-commit` check will be run w/o any changes
* for each PR:
* differences between the current and default (main) branch will be detected
* dependencies between modules and examples will be detected
* `validate` will be run on all changed and dependent modules
* `plan` will be run on all changed and dependent modules
* for each release, on each module and example:
* `validate` will be run
* `apply` will be run
* `plan` will be run on existing infrastructure to test idempotency 
* `destroy` will be run
* any of the steps that …

ci: introduce end2end tests with terraform plan/apply

---

.pre-commit-config.yaml
examples/common_vmseries/README.md
examples/dedicated_vmseries/README.md
examples/dedicated_vmseries_and_autoscale/README.md
examples/standalone_panorama/README.md
examples/standalone_vmseries/README.md
modules/appgw/README.md
modules/application_insights/README.md
modules/bootstrap/README.md
modules/loadbalancer/README.md
modules/natgw/README.md
modules/panorama/README.md
modules/virtual_machine/.README.md
modules/vmseries/README.md
modules/vmss/README.md
modules/vnet/README.md

- Updating pre-commit to increase markdown header indentation from default 2 to 3
- Updated all READMEs via a new pre-commit execution to make the indentation changes
- Updated all REAMDEs to be ready for SWFW Hub with a new level 2 header for `Reference`
All changes in this PR support the go-live for the SWFW Hub
Tested locally
- Docs
- Pre-commit

docs: Update pre-commit and REAMDEs for SWFW Hub

---

.github/actions/plan_apply/action.yml

Avoid provider registration with Terraform. 
When terraform is 1st run against a subscription, the Azure resource provider tries to register all resource providers, regardless if they will be used or not. For automation purposes, when the account has limited access, this will cause the CI workflow to fail.
To avoid that, the `skip_provider_registration` property can be used in the provider block to control that functionality. Since this would require modifications to all examples, an environment variable `ARM_SKIP_PROVIDER_REGISTRATION=true` will be used in the plan/apply action instead.
A risk that the CI will fail due to missing resource providers is minimum because:
- all examples were already deployed in the subscription used by the CI workflows
- we use quite typical resources - …

ci: skip provider registration during plan/apply

---

.github/workflows/apply-command.yml
.github/workflows/idempotence-command.yml
.github/workflows/plan-command.yml
.github/workflows/pr_ci.yml
.github/workflows/pre-commit-update.yml
.github/workflows/release_ci.yml
.github/workflows/sca-command.yml
.github/workflows/validate-command.yml

Bump reusable workflows to newer release
[This patch release](https://github.com/PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/releases/tag/v2.1.2) fixes release CI workflow.
Azure repo copy

ci: bump workflows to newer release

---

.github/workflows/chatops.yml

A personal access token is not suitable to be used with the peter-evans/slash-command-dispatch@v3 action.
This will introduce a step to generate a token via a GitHub App in place of a PAT.

ci: Use a GitHub App for chatops token

---

.github/workflows/chatops.yml

Get away from using PAT or GH apps for chatops workflows.
Less maintenance, more security. Available since [this post](https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/) was published
azure repo copy

ci: move to gh tokens in chatops

---

examples/common_vmseries/main_test.go
examples/common_vmseries_and_autoscale/main_test.go
examples/dedicated_vmseries/main_test.go
examples/dedicated_vmseries_and_autoscale/main_test.go
examples/gwlb_with_vmseries/main_test.go
examples/standalone_panorama/main_test.go
examples/standalone_vmseries/main_test.go
go.mod
go.sum

Introduce changes required by the recent test skeleton release
The latest release of the test skeleton introduced a unified function to generate unique names. This PR is introducing the necessary changes to Terratest code to use that function.
Changes can be tested either locally, or using ChatOps. This PR will not trigger Terraform Code tests.

test: introduce changes required by the recent test skeleton release

---

modules/gwlb/README.md

GWLB module doesn't have the title in README causing Hub sync orchestration action to fail.
Adding a short description to make the sync work.
```
DEBUG:root:Processing file: terraform-azurerm-vmseries-modules/modules/vmseries/README.md
DEBUG:root:Processing file: terraform-azurerm-vmseries-modules/modules/gwlb/README.md
Traceback (most recent call last):
File "/home/runner/work/automation-metadata-collector/automation-metadata-collector/./scripts/process_modules_readmes.py", line 513, in <module>
main(args.modules_directory, args.dest_directory, args.type)
File "/home/runner/work/automation-metadata-collector/automation-metadata-collector/./scripts/process_modules_readmes.py", line 474, in main
tf_modules = get_module_readme_files(Path(modules_directory))
File …
```

docs(modules/gwlb): update README for SWFW Hub

---

.github/workflows/chatops.yml

PR delivers fix for ChatOps - execute ChatOps logic (token, dispatch etc.) only if comment is from pull request and skip comments from issues
Currently ChatOps action is failing for every comment in issues.
Code was tested on internal clone of the repository.

ci: Skip ChatOps steps for comments in issues

---

.github/workflows/apply-command.yml
.github/workflows/chatops.yml
.github/workflows/idempotence-command.yml
.github/workflows/lint_pr_title.yml
.github/workflows/plan-command.yml
.github/workflows/pr_ci.yml
.github/workflows/pre-commit-update.yml
.github/workflows/release_ci.yml
.github/workflows/sca-command.yml
.github/workflows/validate-command.yml

Increase `apply_timeout` for infrastructure building workflows.
Since our code can sometimes be quite complex, default 30 minutes might not be enough to perform apply or idempotence tests. This gives an option to override this property from the calling workflow level.
Additionally, chatops command had no possibility to override this parameter. This change adds that possibility. 
> [!Important]
> DO NOT MERGE BEFORE -> https://github.com/PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/pull/72
tested on Azure repo copy
- CI

ci: increase the default apply timeout

---

examples/common_vmseries/main.tf
examples/common_vmseries_and_autoscale/main.tf
examples/dedicated_vmseries/main.tf
examples/dedicated_vmseries_and_autoscale/main.tf
examples/gwlb_with_vmseries/main.tf
examples/standalone_panorama/main.tf
examples/standalone_vmseries/main.tf
examples/test_infrastructure/example.tfvars
examples/test_infrastructure/main.tf
examples/test_infrastructure/variables.tf
examples/vnet/main.tf
modules/vnet_peering/.header.md
modules/vnet_peering/README.md
modules/vnet_peering/main.tf
modules/vnet_peering/variables.tf
modules/vnet_peering/versions.tf

PR delivers changes for vnet_peering:
- `README.md` adjusted to new style with additional header file
- minimum Terraform version set to 1.3
- refactor variables:
- descriptions
- types with optionals
- default values
- validations
- simplify `main.tf` by removing not required `try`
- remove name generation logic from the module
- add terraform registry reference
#336 
I checked that module using "test_infrastructure" example.

refactor(module/vnet_peering)!: module refactor and adjusted examples

---

examples/gwlb_with_vmseries/example.tfvars

Change region to North Europe for GWLB example.
For whatever reason terraform has problems with refreshing state when a storage account is created in East US region. THis causes the Release CI to constantly fail. The problem is repeatable but affects only East US. Hence changing the example region to North Europe.
locally and chatops

chore(example/gwlb): change region to europe

---

examples/standalone_panorama/main.tf
modules/panorama/main.tf

A fix for how we are handling the bootstrap storage in the panorama module. 
As pointed out by @PenDrag0n7 (#364), the module is not usable with the default values. The problematic part was the condition around bootstrap storage uri parameter that did not allow a default null.
A workaround found in the Panorama example was removed and example was deployed.

fix(examples/standalone_panorama): fix to be deployable with the defaults
